#
# Source this file from ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Get the path of this script file
# https://stackoverflow.com/a/12197518
pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
while([ -h "${SCRIPT_PATH}" ]); do
    cd "`dirname "${SCRIPT_PATH}"`"
    SCRIPT_PATH="$(readlink "`basename "${SCRIPT_PATH}"`")";
done
cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
SCRIPT_PATH="`pwd`";
popd  > /dev/null

# include bashrc.d files
for f in $SCRIPT_PATH/bashrc.d/*; do source $f; done

